# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "dimensions"
client_id = "2799fbccecded86b8741bf595c244555"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-10"

[app_proxy]
url = "https://dimensions-backend-wo1h.onrender.com/"
subpath = "server"
prefix = "a"

[pos]
embedded = false

[build]
dev_store_url = "squirrels-and-squirrels.myshopify.com"
