export const defaultValues = {
 standard: false,
 a: '',
 b: '',
 c: '',
 year: 2023,
 make: '',
 model: '',
 doors: '2DOOR',
 class: 'MIDSIZE',
 customText: false,
 customTextField: '',
 notesField:'',
 business: false,
 logo: false,
 vector: false,
 nonVector: false,
 designLogo: false,
 businessName: '',
 slogan: '',
 city: '',
 state: '',
 phone: '',
 website: '',
}
